USE SQL_Blog_Post;

--CFD groups, breaking the data up into categories to see how much of each we have.

--how many of each occur?

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP like '%ANIMAL BITES%'
--376

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP like '%ASSAULT%'
-- 3805 *COMBINING THE ASSAULT CATEGORIES

select CFD_INCIDENT_TYPE_GROUP
from cincifire
where CFD_INCIDENT_TYPE_GROUP like '%BOMB REMOVAL%'
--Bomb removal 92

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE LIKE '%fire%'
--34627 *combining fire incidents

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%CONVULSIONS%'

--9105

SELECT CFD_INCIDENT_TYPE_GROUP	
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%DIABETIC%'
--5564

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%DOMESTIC VIOLENCE%'
--470

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%HEROIN%' OR CFD_INCIDENT_TYPE_GROUP LIKE '%OVERDOSE%'
--8127 *COMBINED HEROIN AND OVERDOSE/POISONING

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%PSYCHIATRIC%'
--118

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%RAPE%'
-- 70 *COMBINED RAPE W/ INJURY AND RAPE

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%SHOOTING%'
--1088

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%STAB%'
-- 96

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%SUICIDE ATTEMPT%'
-- 2002 COMBINES THE PSYCHIATRIC

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%SWAT%'
-- 220

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%TASING%'
--469

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%TRANSFER CALL%'
-- 1

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%TRAUMATIC INJURIES%'
-- 3035

SELECT CFD_INCIDENT_TYPE_GROUP
FROM cincifire
WHERE CFD_INCIDENT_TYPE_GROUP LIKE '%FAINT%'
-- 10725


--Checking the results displayed on my Tableau viz;

--Slide 1: 9 Assault with Injury incidents in Mt. Adams:

SELECT NEIGHBORHOOD, CFD_INCIDENT_TYPE_GROUP, count(EVENT_NUMBER)
FROM cincifire
WHERE NEIGHBORHOOD = 'Mt. Adams' and CFD_INCIDENT_TYPE_GROUP = 'ASSAULT WITH INJURY'
GROUP BY NEIGHBORHOOD, CFD_INCIDENT_TYPE_GROUP 
ORDER BY count(EVENT_NUMBER) desc;
--tableau= 11 SQL= 11 

--Slide 2: Year Distinct Count Totals;

SELECT year(CREATE_TIME_INCIDENT) as years, count(EVENT_NUMBER)
FROM cincifire
GROUP BY year(CREATE_TIME_INCIDENT)
ORDER BY years desc

/*
2019	17671
2018	62687 tableau = 62,686
2017	61986
2016	58652
2015	57369
*/

-- Break it down further to the months...

SELECT year(CREATE_TIME_INCIDENT) as Years, MONTH(CREATE_TIME_INCIDENT) AS Months, count(EVENT_NUMBER)
FROM cincifire
WHERE year(CREATE_TIME_INCIDENT) = '2018'
GROUP BY year(CREATE_TIME_INCIDENT), MONTH(CREATE_TIME_INCIDENT) 
ORDER BY Years desc, Months asc

-- SQL = January 5,804; tableau = January 5,803
-- Time to break it down to days in the month... and then we will continue to break it down until
-- we find the single entry that is causing issues. 


SELECT  DAY(CREATE_TIME_INCIDENT) AS Days_,
		count(EVENT_NUMBER)
FROM cincifire
WHERE year(CREATE_TIME_INCIDENT) = '2018' and MONTH(CREATE_TIME_INCIDENT) like '1'
GROUP BY year(CREATE_TIME_INCIDENT), 
		MONTH(CREATE_TIME_INCIDENT),
		DAY(CREATE_TIME_INCIDENT) 
ORDER BY Days_ asc

-- Only display the hours for October (10)

SELECT  DATEPART(hour, CREATE_TIME_INCIDENT) AS Hours_,
		count(EVENT_NUMBER)
FROM cincifire
WHERE year(CREATE_TIME_INCIDENT) = '2018' and 
		MONTH(CREATE_TIME_INCIDENT) like '1' and 
		DAY(CREATE_TIME_INCIDENT) like '10'
GROUP BY year(CREATE_TIME_INCIDENT), 
		MONTH(CREATE_TIME_INCIDENT),
		DAY(CREATE_TIME_INCIDENT), 
		DATEPART(hour, CREATE_TIME_INCIDENT)
ORDER BY Hours_ asc

--Show all records



--Slide 3: January = highest amount of incidents in the year? 
-- each day has 1,600 -2,200 incidents?

SELECT MONTH(CREATE_TIME_INCIDENT) AS Months, count(EVENT_NUMBER) as num_of_incidents
FROM cincifire
GROUP BY MONTH(CREATE_TIME_INCIDENT) 
ORDER BY num_of_incidents desc

-- SQL = 24800 tableau = ?

SELECT YEAR(CREATE_TIME_INCIDENT) AS Years, 
		DAY(CREATE_TIME_INCIDENT) AS Day_, 
		count(EVENT_NUMBER) AS num_of_incidents
FROM cincifire
WHERE YEAR(CREATE_TIME_INCIDENT) NOT LIKE '2019' AND
		DAY(CREATE_TIME_INCIDENT) NOT LIKE '31'		
GROUP BY YEAR(CREATE_TIME_INCIDENT), DAY(CREATE_TIME_INCIDENT) 
ORDER BY num_of_incidents desc

-- Is the range between 1,600 and 2,200, excluding 2019?
-- SQL = yes tableau = yes

--Slide 4: Westwood is the neighborhood with the most incidents?

SELECT NEIGHBORHOOD, CFD_INCIDENT_TYPE_GROUP, count(EVENT_NUMBER) as num_of_incidents
FROM cincifire
WHERE NEIGHBORHOOD = 'Westwood'
GROUP BY NEIGHBORHOOD, CFD_INCIDENT_TYPE_GROUP
ORDER BY num_of_incidents desc

/*
WESTWOOD	SICK PERSON			2685
WESTWOOD	BREATHING PROBLEMS	2449
WESTWOOD	FALLS				2071
*/--perfect

-- Slide 5: Westwood: Accident with injury= 204?

SELECT NEIGHBORHOOD, CFD_INCIDENT_TYPE_GROUP, count(EVENT_NUMBER) as num_of_incidents
FROM cincifire
WHERE NEIGHBORHOOD = 'Westwood'
GROUP BY NEIGHBORHOOD, CFD_INCIDENT_TYPE_GROUP
ORDER BY CFD_INCIDENT_TYPE_GROUP 

-- SQL = 204 tableau = 204

--Slide 6: With the neighborhood as Westwood, and the CFD_incident_type_group as Assault with injury
-- July for 2015,2016,2017 the total is 4 incidents for each of those years?
-- In August, there is no data for 2018?

SELECT YEAR(CREATE_TIME_INCIDENT) AS Years, 
		MONTH(CREATE_TIME_INCIDENT) AS Months, 
		--NEIGHBORHOOD, 
		--CFD_INCIDENT_TYPE_GROUP, 
		count(EVENT_NUMBER) as num_of_incidents
FROM cincifire
WHERE NEIGHBORHOOD = 'Westwood' AND CFD_INCIDENT_TYPE_GROUP LIKE 'ASSAULT WITH%'--For the second where condition, I can't use '='
GROUP BY YEAR(CREATE_TIME_INCIDENT), MONTH(CREATE_TIME_INCIDENT)  

-- SQL = 4, no data for August for 2018; tableau = 4, no data for August for 2018



